# GitHub repo "Sponsor" button targets. Add or remove entries as more
# funding platforms come online. Format docs:
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [VerburgtJimmy]
ko_fi: jimmyverburgt
